#### ICNet model parameters
context_size: 2048 # samples - left context added to the audio input to avoid convolutional edge effects
fs_audio: 24414.0625 # Hz - sampling rate for the audio input of the model
fs_MUA: 762.939453125 # Hz - sampling rate for the neural response of the model (~1.3 ms time bins)
ds_factor: 32 # downsampling factor of the model (fs_audio / fs_MUA)
p0: 0.00002 # dB SPL reference of 2e-5 Pascal
audio_normalisation: 0.04 # 1/25 normalisation factor applied to the audio inputs
time_normalisation: 0.0000277777777777777791089371117738693328647059388458728790283203125 # 1/36000 normalisation factor applied to the time inputs
decoder_channels: 512 # number of output MUA channels in each branch (decoder)
n_decoders: 9 # number of branches (decoders)
bottleneck_channels: 64 # number of channels in the bottleneck layer
n_classes: 5 # number of probability classes (0-4 MUA spike counts)